  
version: '3.1'
services:
  postgresql:
    image: waltonmax/postgresql:latest
    container_name: postgresql
    network_mode: host
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data/postgresql/data:/var/lib/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "200M"